# Generated by Django 4.0 on 2023-08-03 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Gym', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enquiry',
            old_name='contant',
            new_name='contact',
        ),
    ]
